[helpers]

[git]
depends = []

[git.files]
"git/gitconfig" = "~/.gitconfig"
"git/gitignore" = "~/.gitignore"

[git.variables]

[nvim]
depends = []

[nvim.files]
"nvim/init.lua" = "~/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"
"nvim/lua/config/lazy.lua" = "~/.config/nvim/lua/config/lazy.lua"
"nvim/lua/plugins/mini-surround.lua" = "~/.config/nvim/lua/plugins/mini-surround.lua"

[nvim.files."nvim/lua/plugins/hop.lua"]
target = "~/.config/nvim/lua/plugins/hop.lua"
type = "symbolic"

[nvim.variables]

[fish]
depends = []

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"
"fish/completions" = "~/.config/fish/completions"
"fish/conf.d" = "~/.config/fish/conf.d"
# Note: fish/functions is managed directly as a directory symlink in setup.sh

[fish.variables]

[zellij]
depends = []

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"

[zellij.variables]

[htop]
depends = []

[htop.files]
"htop/htoprc" = "~/.config/htop/htoprc"

[htop.variables]

[asdf]
depends = []

[asdf.files]
"asdf/.tool-versions" = "~/.tool-versions"

[asdf.variables]

[settings]
default_target_type = "automatic"
